### ISSUE TITLE
雑談にどうぞ

### ISSUE THREAD

**Issue by htppp** [htppp/RaidShare#1]
雑談はここでしましょう_(:3 」∠ )_

**Comment by rtudnns** [comment]
🔃ここに来るのは初めてです。🔃

**Comment by htppp** [comment]
rtudnnsのほうが表示されてしまって
クリックしないとだれかわからないですね_(:3 」∠ )_
悲しみです_(:3 」∠ )_
![image](https://user-images.githubusercontent.com/39856549/106037316-dc1e9300-6119-11eb-9db3-71e2bcb96125.png)

![image](https://user-images.githubusercontent.com/39856549/106037288-d4f78500-6119-11eb-9372-41a3e1fdceef.png)

**Comment by htppp** [comment]
issueじゃなくてdiscussionのほうもチャットができるのですが
何がちがうのやら_(:3 」∠ )_
https://github.com/htppp/RaidShare/discussions/5

**Comment by rtudnns** [comment]
ぴえん

**Comment by htppp** [comment]
スマホアプリも悪くないですね _(:3 」∠ )_

**Comment by htppp** [comment]
ディスカッションのほうがよさげなので
そっちにしましょうか_(:3 」∠ )_
issueはつぶします_(:3 」∠ )_

**Comment by htppp** [comment]
issueつぶすと画像ペタペタできなかったので形だけ残します_(:3 」∠ )_
